"""
Model Consensus – Multi-Model Agreement Engine

Runs student inputs through all 3 primary models (Logistic Regression, Random Forest, XGBoost),
collects predictions and prediction confidence/probabilities, computes majority voting consensus,
and evaluates multi-model alignment with safe fallbacks.
"""

from typing import Dict, Any, List, Optional, Union
import numpy as np

MODELS_IN_CONSENSUS = ["Logistic Regression", "Random Forest", "XGBoost"]


def predict_with_all_models(student_data: Dict[str, Any]) -> Dict[str, Dict[str, Any]]:
    """
    Runs the same student input through all 3 existing models:
    1. Logistic Regression with L2 Regularization
    2. Random Forest
    3. XGBoost

    Safely collects individual predictions, confidence (when predict_proba is available),
    and supporting metadata without crashing.
    """
    from backend.ml.predict import PredictionEngine

    results: Dict[str, Dict[str, Any]] = {}

    for model_name in MODELS_IN_CONSENSUS:
        try:
            pred_res = PredictionEngine.predict_single(student_data, model_name=model_name)
            conf = pred_res.get("confidence")

            # Verify whether confidence was generated by predict_proba
            # If model didn't support predict_proba, confidence could be None
            if conf is not None:
                try:
                    conf_float = round(float(conf), 4)
                    conf_pct_display = f"{round(conf_float * 100, 1)}%"
                except (ValueError, TypeError):
                    conf_float = None
                    conf_pct_display = "Confidence unavailable"
            else:
                conf_float = None
                conf_pct_display = "Confidence unavailable"

            results[model_name] = {
                "model_name": model_name,
                "prediction": pred_res.get("risk_category", "Unknown"),
                "predicted_class": pred_res.get("predicted_class", "Unknown"),
                "confidence": conf_float,
                "confidence_display": conf_pct_display,
                "risk_category": pred_res.get("risk_category", "Unknown"),
                "risk_score": pred_res.get("risk_score", 0.0),
                "probabilities": pred_res.get("probabilities", {}),
                "contributing_factors": pred_res.get("contributing_factors", []),
                "error": None,
                "full_result": pred_res
            }
        except Exception as e:
            results[model_name] = {
                "model_name": model_name,
                "prediction": "Error",
                "predicted_class": "Error",
                "confidence": None,
                "confidence_display": "Confidence unavailable",
                "risk_category": "Error",
                "risk_score": 0.0,
                "probabilities": {},
                "contributing_factors": [],
                "error": str(e),
                "full_result": None
            }

    return results


def calculate_model_consensus(
    predictions_input: Union[Dict[str, Any], List[Any]]
) -> Dict[str, Any]:
    """
    Compares model predictions using majority voting.

    Accepts:
      - Dictionary mapping model names to result dicts or prediction strings.
      - List of prediction strings/dicts.

    Returns structured consensus metrics:
      - final_prediction
      - consensus_count (e.g. 3, 2, or 1)
      - total_models (3)
      - models_agree_display (e.g. "3 / 3", "2 / 3")
      - consensus_percentage (e.g. 100.0, 66.67, 33.33)
      - consensus_status:
          * 3/3 -> "Strong Model Consensus"
          * 2/3 -> "Moderate Model Consensus"
          * No clear agreement -> "Model Disagreement – Prediction Uncertain"
      - agreeing_models
      - disagreeing_models
      - disclaimer
    """
    model_predictions_map: Dict[str, str] = {}

    if isinstance(predictions_input, dict):
        for k, v in predictions_input.items():
            if isinstance(v, dict):
                pred_val = v.get("prediction") or v.get("risk_category") or v.get("predicted_class") or "Unknown"
            else:
                pred_val = str(v)
            model_predictions_map[str(k)] = pred_val
    elif isinstance(predictions_input, list):
        for idx, item in enumerate(predictions_input):
            if isinstance(item, dict):
                m_name = item.get("model_name", f"Model {idx+1}")
                pred_val = item.get("prediction") or item.get("risk_category") or item.get("predicted_class") or "Unknown"
            else:
                m_name = MODELS_IN_CONSENSUS[idx] if idx < len(MODELS_IN_CONSENSUS) else f"Model {idx+1}"
                pred_val = str(item)
            model_predictions_map[m_name] = pred_val
    else:
        model_predictions_map = {}

    # Filter out errors or empty predictions if any
    valid_predictions = {
        m: p for m, p in model_predictions_map.items()
        if p and p.lower() not in ["error", "unknown", "none"]
    }

    total_models = len(model_predictions_map) if model_predictions_map else 3

    # Count occurrences of each prediction
    counts: Dict[str, int] = {}
    for p in valid_predictions.values():
        counts[p] = counts.get(p, 0) + 1

    if counts:
        # Sort by count descending
        sorted_counts = sorted(counts.items(), key=lambda x: x[1], reverse=True)
        top_pred, top_count = sorted_counts[0]
    else:
        top_pred, top_count = "Prediction Uncertain", 0

    # Determine consensus status based on majority voting
    if top_count == 3:
        consensus_count = 3
        consensus_percentage = 100.0
        consensus_status = "Strong Model Consensus"
        final_prediction = top_pred
    elif top_count == 2:
        consensus_count = 2
        consensus_percentage = round((2.0 / 3.0) * 100.0, 2)  # 66.67
        consensus_status = "Moderate Model Consensus"
        final_prediction = top_pred
    else:
        # All 3 models predict different classes or no majority agreement
        consensus_count = 1 if top_count == 1 else 0
        consensus_percentage = round((1.0 / 3.0) * 100.0, 2)  # 33.33
        consensus_status = "Model Disagreement – Prediction Uncertain"
        final_prediction = "Prediction Uncertain"

    agreeing_models = [
        m for m, p in valid_predictions.items()
        if final_prediction != "Prediction Uncertain" and p == final_prediction
    ]
    disagreeing_models = [
        m for m, p in valid_predictions.items()
        if m not in agreeing_models
    ]

    return {
        "final_prediction": final_prediction,
        "consensus_count": consensus_count,
        "total_models": total_models,
        "models_agree_display": f"{consensus_count} / {total_models}",
        "consensus_percentage": consensus_percentage,
        "consensus_status": consensus_status,
        "agreeing_models": agreeing_models,
        "disagreeing_models": disagreeing_models,
        "raw_counts": counts,
        "disclaimer": "Model consensus reflects multi-model agreement and does not imply guaranteed accuracy."
    }


def calculate_average_confidence(confidences_or_predictions: Any) -> Optional[float]:
    """
    Calculates average confidence across models:
    average_confidence = (LR confidence + RF confidence + XGBoost confidence) / 3

    If ANY model does not support probability prediction (confidence is None or unavailable),
    returns None ("Confidence unavailable").
    Does NOT invent confidence values.
    """
    confs: List[float] = []

    if isinstance(confidences_or_predictions, dict):
        for val in confidences_or_predictions.values():
            if isinstance(val, dict):
                c = val.get("confidence")
            else:
                c = val
            if c is None:
                return None
            try:
                confs.append(float(c))
            except (ValueError, TypeError):
                return None
    elif isinstance(confidences_or_predictions, (list, tuple)):
        for c in confidences_or_predictions:
            if isinstance(c, dict):
                c = c.get("confidence")
            if c is None:
                return None
            try:
                confs.append(float(c))
            except (ValueError, TypeError):
                return None
    else:
        return None

    if not confs or len(confs) < 3:
        return None

    return round(float(sum(confs) / len(confs)), 4)


def generate_consensus_summary(consensus_data: Dict[str, Any]) -> str:
    """
    Generates a structured, human-readable ASCII summary of model consensus.
    """
    model_preds = consensus_data.get("model_predictions", {})
    final_pred = consensus_data.get("final_prediction", "Unknown")
    agree_display = consensus_data.get("models_agree_display", "N/A")
    pct = consensus_data.get("consensus_percentage", 0.0)
    status = consensus_data.get("consensus_status", "N/A")
    avg_conf = consensus_data.get("average_confidence_display", "Confidence unavailable")

    lines = [
        "----------------------------------------",
        "        🤖 MODEL CONSENSUS",
        "----------------------------------------",
        ""
    ]

    for model_name in MODELS_IN_CONSENSUS:
        m_info = model_preds.get(model_name, {})
        pred = m_info.get("prediction", "Unknown")
        conf_disp = m_info.get("confidence_display", "Confidence unavailable")
        lines.append(f"{model_name}")
        lines.append(f"Prediction: {pred}")
        lines.append(f"Confidence: {conf_disp}")
        lines.append("")

    lines.extend([
        "----------------------------------------",
        f"Final Prediction: {final_pred.upper() if isinstance(final_pred, str) else final_pred}",
        f"Models Agree: {agree_display}",
        f"Consensus: {pct:.2f}%" if isinstance(pct, (int, float)) else f"Consensus: {pct}%",
        f"Average Model Confidence: {avg_conf}",
        "",
        "Status:",
        f"{status}",
        "----------------------------------------",
        "Note: Consensus represents agreement across models and is not equivalent to accuracy."
    ])

    return "\n".join(lines)


def predict_consensus(student_data: Dict[str, Any]) -> Dict[str, Any]:
    """
    Executes the full Model Consensus prediction flow:
      1. Preprocess & run student data through LR, RF, and XGBoost
      2. Collect predictions and confidence scores
      3. Perform majority voting consensus
      4. Compute average confidence
      5. Generate structured summary
      6. Select representative contributing factors & explanations
    """
    from backend.ml.predict import PredictionEngine

    # 1. Run through all 3 models
    model_predictions = predict_with_all_models(student_data)

    # 2. Calculate consensus
    consensus = calculate_model_consensus(model_predictions)

    # 3. Calculate average confidence
    avg_conf = calculate_average_confidence(model_predictions)
    avg_conf_display = f"{round(avg_conf * 100, 1)}%" if avg_conf is not None else "Confidence unavailable"

    consensus["average_confidence"] = avg_conf
    consensus["average_confidence_display"] = avg_conf_display
    consensus["model_predictions"] = model_predictions

    # 4. Generate summary
    consensus["summary_text"] = generate_consensus_summary(consensus)

    # 5. Determine primary result details to anchor explainability & DB saving
    final_pred = consensus["final_prediction"]
    primary_result = None

    # Prefer one of the models that agreed with majority vote
    for model_name in consensus.get("agreeing_models", []):
        m_res = model_predictions.get(model_name, {}).get("full_result")
        if m_res:
            primary_result = m_res
            break

    # If no agreement or uncertain, fall back to best model
    if primary_result is None:
        best_name = PredictionEngine.get_best_model_info().get("best_model_name", "XGBoost")
        primary_result = model_predictions.get(best_name, {}).get("full_result")

    # If still none, fall back to first successful model result
    if primary_result is None:
        for m_data in model_predictions.values():
            if m_data.get("full_result"):
                primary_result = m_data["full_result"]
                break

    student_id = str(student_data.get("student_id") or student_data.get("Student_ID", "STU-NEW"))
    student_name = str(student_data.get("name") or student_data.get("Name", "Student"))

    if primary_result:
        out_dict = dict(primary_result)
    else:
        out_dict = {
            "student_id": student_id,
            "student_name": student_name,
            "predicted_class": "Unknown",
            "confidence": avg_conf or 1.0,
            "risk_category": final_pred,
            "risk_score": 50.0,
            "probabilities": {},
            "contributing_factors": [],
            "input_data": student_data
        }

    # Override risk category with final consensus prediction if a majority exists
    if final_pred != "Prediction Uncertain":
        out_dict["risk_category"] = final_pred
    else:
        out_dict["risk_category"] = "Prediction Uncertain"

    out_dict["model_used"] = "Model Consensus (Majority Voting: LR, RF, XGB)"
    out_dict["consensus"] = consensus

    return out_dict
